apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld-app
        image: us.gcr.io/kaneshin-co/hello-golang:latest
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 8080
