apiVersion: v1
kind: ReplicationController
metadata:
  name: golang
spec:
  replicas: 3
  selector:
    app: golang
  template:
    metadata:
      labels:
        app: golang
    spec:
      containers:
      - name: golang
        image: [container-repository]
        ports:
        - containerPort: 8080
          hostPort: 80
